### ISSUE TITLE
Migliorare il testing

### ISSUE THREAD

**Issue by iannellog** [fioriofederico/labyrinth_22-23#13]
Ho fatto un po' di testing.
Ora l'interfaccia utente è molto migliorata, ma ci sono ancora cose che non vanno.

Riporto di seguito i test che ho effettuate e segnalo che problemi hanno dato. 
La mia impressione è che sarebbe necessario effettuare un testing piuttosto esteso perché le funzionalità che avete inserito sono molte e anche i possibili input sono diversificati.

- i test con le immagini tiff sembrano funzionare correttamente, tranne nel caso del labirinto labirinto2_marked.tiff che va in errore (tra gli esempi mi pare l'unico che ha un punto di partenza da cui non si raggiunge la destinazione e forse è quello il caso non gestito correttamente); l'errore è:

> Traceback (most recent call last):
  File "/Users/iannello/Home/Didattica/Programmazione/2022-2023/Progetti/Calandra-Fiorio-Papa/labyrinth_22-23/main.py", line 251, in <module>
    menu.JsonInput(args.json_path)
  File "/Users/iannello/Home/Didattica/Programmazione/2022-2023/Progetti/Calandra-Fiorio-Papa/labyrinth_22-23/utilities/menuOption.py", line 239, in JsonInput
    generateImage.createImageForASpecifcStartPoint(fileNameImgInput, fileNameImgOutput, i, breadcrumps)
  File "/Users/iannello/Home/Didattica/Programmazione/2022-2023/Progetti/Calandra-Fiorio-Papa/labyrinth_22-23/utilities/generationMazeOutputImage.py", line 55, in createImageForASpecifcStartPoint
    tuple_data = [(x[1], x[0]) for x in self.__movimentPath[startPoint]]
IndexError: list index out of range

- i test con i file json danno a volte risultati diversi rispetto alle immagini (per esempio nel caso del labirinto 30-20_marked e del labirinto labirinto3b_marked) e questo non dovrebbe essere

**Comment by fioriofederico** [comment]
Prof @iannellog  guardi dovremmo aver risolto tutti i problemi aggiustato anche il problema che riguardava la decodifica dei pesi aggiuntivi come le accennavo ieri quello comportava la non risoluzione di tutti i labirinti e anche il ritrovamento dei diversi path. Le chiedo ancora di attendere qualche minuto per fare le prove definitive appena possibile chiuderemo la discussion aperta stamani dal mio collega @vectorstain
