### ISSUE TITLE
Commentare le classi

### ISSUE THREAD

**Issue by iannellog** [fioriofederico/labyrinth_22-23#15]
Vi chiederei di aggiungere un commento sintetico prima del costruttore delle classi:
- menuOption
- GenerationMazeOutputImage
- FoundPath

Che descrivano il ruolo che hanno nell'applicazione (a tal fine forse è utile anche elencare nel commento i metodi più caratteristici della classe) in modo da facilitare il compito di capire la sua organizzazione complessiva.

**Comment by vectorstain** [comment]
Added comments on menuOption, GenerationMazeOutputImage and FoundPath class.
For any other problem please open a issue, our team will solve the problem ASAP.

Regards,
Vincenzo Maria Calandra
