### ISSUE TITLE
Classe Maze

### ISSUE THREAD

**Issue by iannellog** [fioriofederico/labyrinth_22-23#6]
Questio sono solo alcuni suggerimenti migliorativi (la classe ha molti metodi, non li ho esaminati tutti con lo stesso dettaglio)

1. metodo resetMaze: manca il parametro self; di fatto non è un metodo e non si capisce se va eliminato
2. metoti readMazeJSON e readMazeImage: nel commento si dice che non ritornano nulla, ma in realtà ritornano un numpy array e non si capisce perché (per es. nel main l'oggetto restituito non viene utilizzato)

In generale la classe ha moltissimi metodi, la logica complessiva si intuisce, ma non è chiaramente spiegata attraverso i commenti.

**Comment by vectorstain** [comment]
Grazie per il feedback, attualmente il metodo resetMaze() non è implementato ma verrà inserito presto. Per quanto riguarda i metodi readMazeJson() e readMazeImage() essi ritornato un numpy array come utility per gli unittest ma come fa notare effettivamente oltre quello scopo non hanno alcuna funzione all'interno del programma dunque verranno fatte le opportune correzioni. Per quanto riguardo la logica applicativa verranno aggiunti presto dei diagrammi esplicativi relativi al processo di funzionamento.

Si ringrazia per la disponibilità,
Saluti,
Vincenzo Maria Calandra

**Comment by vectorstain** [comment]
Aggiunto metodo resetMaze()

**Comment by vectorstain** [comment]
Sistemate le docstring e i doctest dei metodi readMazeJson() e readMazeImage().
