### ISSUE TITLE
Classe FoundPath

### ISSUE THREAD

**Issue by iannellog** [fioriofederico/labyrinth_22-23#7]
I commenti non mi sembrano adeguati a far capire cosa fa il codice.
Solo alcuni esempi:
- capire la logica del metodo maze2graph è particamente impossibile senza qualche comento esplicativo
- non si capisce il ruolo del metodo heuristic né cosa siano i suoi parametri
- stesso discosro per il metodo find_multi_path_astar_return_visited

**Comment by iannellog** [comment]
Sarebbe opportuna una call. Dimmi quando puoi.
Voglio discutere la parte sul grafo. Posso sentirmi anche solo con te, ma se vogliono partecipare anche gli altri meglio.

**Comment by fioriofederico** [comment]
Potremmo anche organizzarla per domani in tardo pomeriggio verso le 19 se fossero anche disponibili @vectorstain e @Ele9999. Potrebbe essere un punto di confronto e allineamento generico. Aspetto una risposta dai miei colleghi e poi prof in caso possiamo organizzarci

**Comment by vectorstain** [comment]
Buonasera, mi farebbe molto piacere essere presente all’incontro, confermo
la mia disponibilità per l’ora indicata.


Il giorno mer 25 gen 2023 alle 16:55 Federico Fiorio <
***@***.***> ha scritto:
