### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by vectorstain** [fioriofederico/labyrinth_22-23#8]
Realize a more esplicative documentation.

Could be useful to have a sequence diagram and a usecase diagram.

**Comment by fioriofederico** [comment]
Oltre alla documentazione @Ele9999 @vectorstain vediamo di appurare e risolvere dove possibile i todo che ho posto oggi

**Comment by vectorstain** [comment]
Added a use case diagram and updated the readme file with basic instructions.

**Comment by fioriofederico** [comment]
Documentazione del tutto sistemata con anessa creazione del Docker file e compose
